//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3603
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gean.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gean.Data.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 开始事务事务回滚失败! 的本地化字符串。
        /// </summary>
        internal static string BeginTransactionFailed {
            get {
                return ResourceManager.GetString("BeginTransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 改换数据库失败! 的本地化字符串。
        /// </summary>
        internal static string ChangeDatabaseFailed {
            get {
                return ResourceManager.GetString("ChangeDatabaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭数据库连接失败! 的本地化字符串。
        /// </summary>
        internal static string CloseDatabaseFailed {
            get {
                return ResourceManager.GetString("CloseDatabaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺少CommandText(sql语句或存储过程)。 的本地化字符串。
        /// </summary>
        internal static string CommandTextMissing {
            get {
                return ResourceManager.GetString("CommandTextMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交事务失败! 的本地化字符串。
        /// </summary>
        internal static string CommitTransactionFailed {
            get {
                return ResourceManager.GetString("CommitTransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺少查询条件。 的本地化字符串。
        /// </summary>
        internal static string ConditionMissing {
            get {
                return ResourceManager.GetString("ConditionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接字符串不允许为空! 的本地化字符串。
        /// </summary>
        internal static string ConnectionStringMissing {
            get {
                return ResourceManager.GetString("ConnectionStringMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database 实例不存在（即为null）！ 的本地化字符串。
        /// </summary>
        internal static string DatabaseInstanceNotExisting {
            get {
                return ResourceManager.GetString("DatabaseInstanceNotExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该数据类型不被支持。 的本地化字符串。
        /// </summary>
        internal static string DbTypeNotSupport {
            get {
                return ResourceManager.GetString("DbTypeNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entity 不允许为空，请初始化Entity . 的本地化字符串。
        /// </summary>
        internal static string EmptyEntity {
            get {
                return ResourceManager.GetString("EmptyEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体须有主键。 的本地化字符串。
        /// </summary>
        internal static string EntityMustContainPrimaryKey {
            get {
                return ResourceManager.GetString("EntityMustContainPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execute NonQuery 失败! 的本地化字符串。
        /// </summary>
        internal static string ExecuteNonQueryFailed {
            get {
                return ResourceManager.GetString("ExecuteNonQueryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execute Reader 失败! 的本地化字符串。
        /// </summary>
        internal static string ExecuteReaderFailed {
            get {
                return ResourceManager.GetString("ExecuteReaderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execute Scalar 失败! 的本地化字符串。
        /// </summary>
        internal static string ExecuteScalarFailed {
            get {
                return ResourceManager.GetString("ExecuteScalarFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取 DataSet 失败! 的本地化字符串。
        /// </summary>
        internal static string GetDataSetFailed {
            get {
                return ResourceManager.GetString("GetDataSetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取 DataTable 失败! 的本地化字符串。
        /// </summary>
        internal static string GetDataTableFailed {
            get {
                return ResourceManager.GetString("GetDataTableFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父实体缺少ID和主键。 的本地化字符串。
        /// </summary>
        internal static string IDAndPKOfEntityMissing {
            get {
                return ResourceManager.GetString("IDAndPKOfEntityMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父实体须有ID。 的本地化字符串。
        /// </summary>
        internal static string IdentityOfEntityMissing {
            get {
                return ResourceManager.GetString("IdentityOfEntityMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialize gateway failed.CommandExecutor is null. 的本地化字符串。
        /// </summary>
        internal static string InitializeGatewayFailed {
            get {
                return ResourceManager.GetString("InitializeGatewayFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化数据入口失败 !连接字符串不允许为空! 的本地化字符串。
        /// </summary>
        internal static string InitializeGatewayFailedConnectionString {
            get {
                return ResourceManager.GetString("InitializeGatewayFailedConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化数据入口失败 !Entity 不允许为空! 的本地化字符串。
        /// </summary>
        internal static string InitializeGatewayFailedEntity {
            get {
                return ResourceManager.GetString("InitializeGatewayFailedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非法参数，参数不准是 null 。 的本地化字符串。
        /// </summary>
        internal static string InvalidArguments {
            get {
                return ResourceManager.GetString("InvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid database object. 的本地化字符串。
        /// </summary>
        internal static string InvalidDatabaseObject {
            get {
                return ResourceManager.GetString("InvalidDatabaseObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败的数据库类型，无法建立该类型的IDatabase。 的本地化字符串。
        /// </summary>
        internal static string InvalidDatabaseType {
            get {
                return ResourceManager.GetString("InvalidDatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entity 必須有TableAttribute修飾，且 TableName選項不允許為 null . 的本地化字符串。
        /// </summary>
        internal static string InvalidEntityConfig {
            get {
                return ResourceManager.GetString("InvalidEntityConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接数据库失败! 的本地化字符串。
        /// </summary>
        internal static string OpenDatabaseFailed {
            get {
                return ResourceManager.GetString("OpenDatabaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Must provide a sequence for the identity column in oracle. 的本地化字符串。
        /// </summary>
        internal static string OracleSequenceMissing {
            get {
                return ResourceManager.GetString("OracleSequenceMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父实体须有主键。 的本地化字符串。
        /// </summary>
        internal static string ParentEntityMustContainPrimaryKey {
            get {
                return ResourceManager.GetString("ParentEntityMustContainPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实体须有主键。. 的本地化字符串。
        /// </summary>
        internal static string PrimaryKeyMissing {
            get {
                return ResourceManager.GetString("PrimaryKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性类别（数组或非数组）必须与关系类型相符。 的本地化字符串。
        /// </summary>
        internal static string PropertyTypeMustMatchAssociationType {
            get {
                return ResourceManager.GetString("PropertyTypeMustMatchAssociationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在多對一的关系中，RelationAttribute 必須指定外鍵。 的本地化字符串。
        /// </summary>
        internal static string RelationAttributeShouldHasAForeignKey {
            get {
                return ResourceManager.GetString("RelationAttributeShouldHasAForeignKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事务回滚失败! 的本地化字符串。
        /// </summary>
        internal static string RollbackTransactionFailed {
            get {
                return ResourceManager.GetString("RollbackTransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有参数类型必须一致！ 的本地化字符串。
        /// </summary>
        internal static string SameArgumentTypeRequired {
            get {
                return ResourceManager.GetString("SameArgumentTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须先开始一个事务。 的本地化字符串。
        /// </summary>
        internal static string ShouldBeginTransaction {
            get {
                return ResourceManager.GetString("ShouldBeginTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorted order required. 的本地化字符串。
        /// </summary>
        internal static string SortedOrderRequired {
            get {
                return ResourceManager.GetString("SortedOrderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQLTextBuilder Error! 的本地化字符串。
        /// </summary>
        internal static string SQLTextBuilderError {
            get {
                return ResourceManager.GetString("SQLTextBuilderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事务不存在！ 的本地化字符串。
        /// </summary>
        internal static string TransactionNotExisting {
            get {
                return ResourceManager.GetString("TransactionNotExisting", resourceCulture);
            }
        }
    }
}
