//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gean.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gean.Data.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始事务事务回滚失败!.
        /// </summary>
        public static string BeginTransactionFailed {
            get {
                return ResourceManager.GetString("BeginTransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改换数据库失败!.
        /// </summary>
        public static string ChangeDatabaseFailed {
            get {
                return ResourceManager.GetString("ChangeDatabaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭数据库连接失败!.
        /// </summary>
        public static string CloseDatabaseFailed {
            get {
                return ResourceManager.GetString("CloseDatabaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缺少CommandText(sql语句或存储过程)。.
        /// </summary>
        public static string CommandTextMissing {
            get {
                return ResourceManager.GetString("CommandTextMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交事务失败!.
        /// </summary>
        public static string CommitTransactionFailed {
            get {
                return ResourceManager.GetString("CommitTransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缺少查询条件。.
        /// </summary>
        public static string ConditionMissing {
            get {
                return ResourceManager.GetString("ConditionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接字符串不允许为空!.
        /// </summary>
        public static string ConnectionStringMissing {
            get {
                return ResourceManager.GetString("ConnectionStringMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database 实例不存在（即为null）！.
        /// </summary>
        public static string DatabaseInstanceNotExisting {
            get {
                return ResourceManager.GetString("DatabaseInstanceNotExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该数据类型不被支持。.
        /// </summary>
        public static string DbTypeNotSupport {
            get {
                return ResourceManager.GetString("DbTypeNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity 不允许为空，请初始化Entity ..
        /// </summary>
        public static string EmptyEntity {
            get {
                return ResourceManager.GetString("EmptyEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实体须有主键。.
        /// </summary>
        public static string EntityMustContainPrimaryKey {
            get {
                return ResourceManager.GetString("EntityMustContainPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute NonQuery 失败!.
        /// </summary>
        public static string ExecuteNonQueryFailed {
            get {
                return ResourceManager.GetString("ExecuteNonQueryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Reader 失败!.
        /// </summary>
        public static string ExecuteReaderFailed {
            get {
                return ResourceManager.GetString("ExecuteReaderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Scalar 失败!.
        /// </summary>
        public static string ExecuteScalarFailed {
            get {
                return ResourceManager.GetString("ExecuteScalarFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取 DataSet 失败!.
        /// </summary>
        public static string GetDataSetFailed {
            get {
                return ResourceManager.GetString("GetDataSetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取 DataTable 失败!.
        /// </summary>
        public static string GetDataTableFailed {
            get {
                return ResourceManager.GetString("GetDataTableFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 父实体缺少ID和主键。.
        /// </summary>
        public static string IDAndPKOfEntityMissing {
            get {
                return ResourceManager.GetString("IDAndPKOfEntityMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 父实体须有ID。.
        /// </summary>
        public static string IdentityOfEntityMissing {
            get {
                return ResourceManager.GetString("IdentityOfEntityMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize gateway failed.CommandExecutor is null..
        /// </summary>
        public static string InitializeGatewayFailed {
            get {
                return ResourceManager.GetString("InitializeGatewayFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化数据入口失败 !连接字符串不允许为空!.
        /// </summary>
        public static string InitializeGatewayFailedConnectionString {
            get {
                return ResourceManager.GetString("InitializeGatewayFailedConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化数据入口失败 !Entity 不允许为空!.
        /// </summary>
        public static string InitializeGatewayFailedEntity {
            get {
                return ResourceManager.GetString("InitializeGatewayFailedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非法参数，参数不准是 null 。.
        /// </summary>
        public static string InvalidArguments {
            get {
                return ResourceManager.GetString("InvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid database object..
        /// </summary>
        public static string InvalidDatabaseObject {
            get {
                return ResourceManager.GetString("InvalidDatabaseObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失败的数据库类型，无法建立该类型的IDatabase。.
        /// </summary>
        public static string InvalidDatabaseType {
            get {
                return ResourceManager.GetString("InvalidDatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity 必須有TableAttribute修飾，且 TableName選項不允許為 null ..
        /// </summary>
        public static string InvalidEntityConfig {
            get {
                return ResourceManager.GetString("InvalidEntityConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接数据库失败!.
        /// </summary>
        public static string OpenDatabaseFailed {
            get {
                return ResourceManager.GetString("OpenDatabaseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide a sequence for the identity column in oracle..
        /// </summary>
        public static string OracleSequenceMissing {
            get {
                return ResourceManager.GetString("OracleSequenceMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 父实体须有主键。.
        /// </summary>
        public static string ParentEntityMustContainPrimaryKey {
            get {
                return ResourceManager.GetString("ParentEntityMustContainPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实体须有主键。..
        /// </summary>
        public static string PrimaryKeyMissing {
            get {
                return ResourceManager.GetString("PrimaryKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性类别（数组或非数组）必须与关系类型相符。.
        /// </summary>
        public static string PropertyTypeMustMatchAssociationType {
            get {
                return ResourceManager.GetString("PropertyTypeMustMatchAssociationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在多對一的关系中，RelationAttribute 必須指定外鍵。.
        /// </summary>
        public static string RelationAttributeShouldHasAForeignKey {
            get {
                return ResourceManager.GetString("RelationAttributeShouldHasAForeignKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事务回滚失败!.
        /// </summary>
        public static string RollbackTransactionFailed {
            get {
                return ResourceManager.GetString("RollbackTransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有参数类型必须一致！.
        /// </summary>
        public static string SameArgumentTypeRequired {
            get {
                return ResourceManager.GetString("SameArgumentTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必须先开始一个事务。.
        /// </summary>
        public static string ShouldBeginTransaction {
            get {
                return ResourceManager.GetString("ShouldBeginTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted order required..
        /// </summary>
        public static string SortedOrderRequired {
            get {
                return ResourceManager.GetString("SortedOrderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLTextBuilder Error!.
        /// </summary>
        public static string SQLTextBuilderError {
            get {
                return ResourceManager.GetString("SQLTextBuilderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当使用In子句时，Value必需是SQLTextBuilder.InTextBuilder类型。.
        /// </summary>
        public static string SQLTextBuilderError_In {
            get {
                return ResourceManager.GetString("SQLTextBuilderError_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 事务不存在！.
        /// </summary>
        public static string TransactionNotExisting {
            get {
                return ResourceManager.GetString("TransactionNotExisting", resourceCulture);
            }
        }
    }
}
