//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gean.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SQLString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gean.Data.Resources.SQLString", typeof(SQLString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select * From dbo.{0} Where ({1} = @ID).
        /// </summary>
        public static string FindById {
            get {
                return ResourceManager.GetString("FindById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select * From dbo.{0}.
        /// </summary>
        public static string GetAll {
            get {
                return ResourceManager.GetString("GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	TABLE_NAME AS &apos;TableName&apos;,
        ///	COLUMN_NAME AS &apos;ColumsName&apos;,
        ///	DATA_TYPE AS &apos;DbDataType&apos;,
        ///	IS_NULLABLE AS &apos;IsNull&apos;,
        ///	isnull(isnull(isnull(CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION), DATETIME_PRECISION),1) AS &apos;Length&apos;,
        ///	COLUMN_DEFAULT AS &apos;DefalutValue&apos;
        ///FROM
        ///	INFORMATION_SCHEMA.COLUMNS
        ///WHERE
        ///	TABLE_NAME = @TableName.
        /// </summary>
        public static string GetColumnsByTable {
            get {
                return ResourceManager.GetString("GetColumnsByTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	v_o.name AS &apos;ViewName&apos;, /*视图名*/
        ///	t_o.name AS &apos;CorrelativeTableName&apos;, /*相关的表名*/
        ///	v_c.name AS &apos;ViewColumnName&apos;, /*视图中的列名*/
        ///	t_c.name AS &apos;CorrelativeFieldName&apos; /*相关的表中的字段名*/
        ///FROM 
        ///	sysdepends d,
        ///	sysobjects v_o,
        ///	syscolumns v_c,
        ///	sysobjects t_o,
        ///	syscolumns t_c 
        ///WHERE 
        ///	objectproperty(d.id,&apos;IsView&apos;) = 1 
        ///	and d.id = v_o.id and v_o.id = v_c.id 
        ///	and d.depnumber = v_c.colid 
        ///	and d.depid = t_o.id and t_o.id = t_c.id 
        ///	and d.depnumber = t_c.colid 
        ///	and v_o.name = @ViewName	/*要查询的视图名*/
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetInfoByView {
            get {
                return ResourceManager.GetString("GetInfoByView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	o.name AS &apos;TableName&apos;,
        ///	c.name AS &apos;FieldName&apos;,
        ///	k.colid AS &apos;FieldNumber&apos;,
        ///	k.keyno AS &apos;IndexedSequential&apos;, /*索引顺序*/
        ///	t.name AS &apos;DbDataType&apos;
        ///FROM 
        ///	sysindexes i
        ///	join sysindexkeys k on i.id = k.id and i.indid = k.indid
        ///	join sysobjects o on i.id = o.id
        ///	join syscolumns c on i.id = c.id and k.colid = c.colid
        ///	join systypes t on c.xusertype = t.xusertype
        ///WHERE 
        ///	o.xtype = &apos;U&apos; and o.name= @TableName
        ///	and exists
        ///		(SELECT 1 FROM sysobjects WHERE xtype = &apos;PK&apos; and parent_obj = i.id and name [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetPrimaryKeyByTable {
            get {
                return ResourceManager.GetString("GetPrimaryKeyByTable", resourceCulture);
            }
        }
    }
}
