//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3603
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gean.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SQLString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLString() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gean.Data.Resources.SQLString", typeof(SQLString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Select * From dbo.{0} Where ({1} = @ID) 的本地化字符串。
        /// </summary>
        public static string FindById {
            get {
                return ResourceManager.GetString("FindById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select * From dbo.{0} 的本地化字符串。
        /// </summary>
        public static string GetAll {
            get {
                return ResourceManager.GetString("GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT
        ///	TABLE_NAME AS &apos;TableName&apos;,
        ///	COLUMN_NAME AS &apos;ColumsName&apos;,
        ///	DATA_TYPE AS &apos;DbDataType&apos;,
        ///	IS_NULLABLE AS &apos;IsNull&apos;,
        ///	isnull(isnull(isnull(CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION), DATETIME_PRECISION),1) AS &apos;Length&apos;,
        ///	COLUMN_DEFAULT AS &apos;DefalutValue&apos;
        ///FROM
        ///	INFORMATION_SCHEMA.COLUMNS
        ///WHERE
        ///	TABLE_NAME = @TableName 的本地化字符串。
        /// </summary>
        public static string GetColumnsByTable {
            get {
                return ResourceManager.GetString("GetColumnsByTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT 
        ///	v_o.name AS &apos;ViewName&apos;, /*视图名*/
        ///	t_o.name AS &apos;CorrelativeTableName&apos;, /*相关的表名*/
        ///	v_c.name AS &apos;ViewColumnName&apos;, /*视图中的列名*/
        ///	t_c.name AS &apos;CorrelativeFieldName&apos; /*相关的表中的字段名*/
        ///FROM 
        ///	sysdepends d,
        ///	sysobjects v_o,
        ///	syscolumns v_c,
        ///	sysobjects t_o,
        ///	syscolumns t_c 
        ///WHERE 
        ///	objectproperty(d.id,&apos;IsView&apos;) = 1 
        ///	and d.id = v_o.id and v_o.id = v_c.id 
        ///	and d.depnumber = v_c.colid 
        ///	and d.depid = t_o.id and t_o.id = t_c.id 
        ///	and d.depnumber = t_c.colid 
        ///	and v_o.name = @ViewName	/*要查询的视图名*/
        ///	 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string GetInfoByView {
            get {
                return ResourceManager.GetString("GetInfoByView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT 
        ///	o.name AS &apos;TableName&apos;,
        ///	c.name AS &apos;FieldName&apos;,
        ///	k.colid AS &apos;FieldNumber&apos;,
        ///	k.keyno AS &apos;IndexedSequential&apos;, /*索引顺序*/
        ///	t.name AS &apos;DbDataType&apos;
        ///FROM 
        ///	sysindexes i
        ///	join sysindexkeys k on i.id = k.id and i.indid = k.indid
        ///	join sysobjects o on i.id = o.id
        ///	join syscolumns c on i.id = c.id and k.colid = c.colid
        ///	join systypes t on c.xusertype = t.xusertype
        ///WHERE 
        ///	o.xtype = &apos;U&apos; and o.name= @TableName
        ///	and exists
        ///		(SELECT 1 FROM sysobjects WHERE xtype = &apos;PK&apos; and parent_obj = i.id and name [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string GetPrimaryKeyByTable {
            get {
                return ResourceManager.GetString("GetPrimaryKeyByTable", resourceCulture);
            }
        }
    }
}
