//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gean.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ArgumentValidationString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArgumentValidationString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gean.Resources.ArgumentValidationString", typeof(ArgumentValidationString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数值必须大于0字节。.
        /// </summary>
        internal static string ExceptionByteArrayValueMustBeGreaterThanZeroBytes {
            get {
                return ResourceManager.GetString("ExceptionByteArrayValueMustBeGreaterThanZeroBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数 &apos;{0}&apos;的值不能为空字符串。.
        /// </summary>
        internal static string ExceptionEmptyString {
            get {
                return ResourceManager.GetString("ExceptionEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}不是{1}的一个有效值。.
        /// </summary>
        internal static string ExceptionEnumerationNotDefined {
            get {
                return ResourceManager.GetString("ExceptionEnumerationNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无效的类型，期待的类型必须为&apos;{0}&apos;。.
        /// </summary>
        internal static string ExceptionExpectedType {
            get {
                return ResourceManager.GetString("ExceptionExpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数&apos;{0}&apos;的名称不能为空引用或空字符串。.
        /// </summary>
        internal static string ExceptionInvalidNullNameArgument {
            get {
                return ResourceManager.GetString("ExceptionInvalidNullNameArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 变量&apos;{0}&apos;的值必须是0或者1。.
        /// </summary>
        internal static string ValueMustIs0or1 {
            get {
                return ResourceManager.GetString("ValueMustIs0or1", resourceCulture);
            }
        }
    }
}
