//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3603
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gean.OrientalCharacters.Service {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringService() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gean.OrientalCharacters.Service.StringService", typeof(StringService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 主窗体已关闭 的本地化字符串。
        /// </summary>
        public static string CoreWorkbenchAlreadyClosed {
            get {
                return ResourceManager.GetString("CoreWorkbenchAlreadyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主窗体已显示 的本地化字符串。
        /// </summary>
        public static string CoreWorkbenchGettingOpened {
            get {
                return ResourceManager.GetString("CoreWorkbenchGettingOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序服务管理器启动完成. 的本地化字符串。
        /// </summary>
        public static string ServiceManagerActivated {
            get {
                return ResourceManager.GetString("ServiceManagerActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序服务管理器开始启动. 的本地化字符串。
        /// </summary>
        public static string ServiceManagerGettingStarted {
            get {
                return ResourceManager.GetString("ServiceManagerGettingStarted", resourceCulture);
            }
        }
    }
}
